import { Button } from '@/components/ui/button'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CalendarIcon, FolderIcon, InboxIcon, MenuIcon, PlusIcon } from 'lucide-react'
import { MenuButton } from '@/components/MenuButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header className="px-4 py-2 border-b flex justify-between">
          <div className="flex items-center space-x-2">
            <Button size="icon" variant="ghost">
              <MenuIcon />
            </Button>
            <h1 className="text-xl font-semibold">To Do</h1>
          </div>

          <Button size="icon" variant="ghost">
            <PlusIcon />
          </Button>
        </header>
        <div className="flex flex-1">
          <div className="w-80 border-r flex flex-col p-2">
            <MenuButton.Root icon={InboxIcon} href="#">
              Index 
            </MenuButton.Root>
            <MenuButton.Root icon={CalendarIcon} href="#">
              Today
            </MenuButton.Root>
            <div className='flex justify-between px-4 py-2 text-muted-foreground'>
              <p className='text-sm font-medium'>Projects</p>
              <PlusIcon className="h-5 w-5" />
            </div>
            <MenuButton.Root icon={FolderIcon} href="#">
              Project One
              <MenuButton.MoreButton />
            </MenuButton.Root>
            <MenuButton.Root icon={FolderIcon} href="#">
              Project Two
              <MenuButton.MoreButton />
            </MenuButton.Root>
            <MenuButton.Root icon={FolderIcon} href="#">
              Project Three
              <MenuButton.MoreButton />
            </MenuButton.Root>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
